// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SMMS.Repositories.NghiaHT.Models;

public partial class CheckUpScheduleHuyLq
{
    public int CheckupScheduleHuyLqid { get; set; }

    public string CheckUpName { get; set; }

    public string Description { get; set; }

    public virtual ICollection<MedicalCheckupHuyLq> MedicalCheckupHuyLqs { get; set; } = new List<MedicalCheckupHuyLq>();
}