// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SMMS.Repositories.NghiaHT.Models;

public partial class HealthProfileTypesTienVln
{
    public int HealthProfileTypesTienVlnid { get; set; }

    public string HealthProfileName { get; set; }

    public string Description { get; set; }

    public virtual ICollection<StudentHealthProfilesTienVln> StudentHealthProfilesTienVlns { get; set; } = new List<StudentHealthProfilesTienVln>();
}