// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SMMS.Repositories.NghiaHT.Models;

public partial class MedicationQuanTn
{
    public int MedicationQuanTnid { get; set; }

    public string MedicationName { get; set; }

    public string GenericName { get; set; }

    public int? MedicationCategoryQuanTnid { get; set; }

    public string Form { get; set; }

    public int? Quantity { get; set; }

    public string Strength { get; set; }

    public string Indications { get; set; }

    public string Contraindications { get; set; }

    public string SideEffects { get; set; }

    public DateTime? StartDate { get; set; }

    public bool? IsApproved { get; set; }

    public virtual MedicationCategoryQuanTn MedicationCategoryQuanTn { get; set; }
}