// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SMMS.Repositories.NghiaHT.Models;

public partial class MedicalEventPhucTm
{
    public int MedicalEventPhucTmid { get; set; }

    public int? EventTypePhucTmid { get; set; }

    public DateTime? OccurredAt { get; set; }

    public string ReportedBy { get; set; }

    public string Description { get; set; }

    public string Symptoms { get; set; }

    public decimal? Temperature { get; set; }

    public string BloodPressure { get; set; }

    public int? HeartRate { get; set; }

    public bool? FirstAidGiven { get; set; }

    public string FirstAidDetails { get; set; }

    public bool? ParentNotified { get; set; }

    public string FollowUpNote { get; set; }

    public virtual EventTypePhucTm EventTypePhucTm { get; set; }
}