// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SMMS.Repositories.NghiaHT.Models;

public partial class MedicationCategoryQuanTn
{
    public int MedicationCategoryQuanTnid { get; set; }

    public string CategoryName { get; set; }

    public string Description { get; set; }

    public virtual ICollection<MedicationQuanTn> MedicationQuanTns { get; set; } = new List<MedicationQuanTn>();

    public virtual ICollection<RequestNghiaHt> RequestNghiaHts { get; set; } = new List<RequestNghiaHt>();
}