// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SMMS.Repositories.NghiaHT.Models;

public partial class MedicalCheckupHuyLq
{
    public int CheckupHuyLqid { get; set; }

    public int? CheckupScheduleHuyLqid { get; set; }

    public DateTime? CheckupDate { get; set; }

    public decimal? Height { get; set; }

    public decimal? Weight { get; set; }

    public decimal? Bmi { get; set; }

    public string BloodType { get; set; }

    public int? VisionLeft { get; set; }

    public int? VisionRight { get; set; }

    public string HearingLeft { get; set; }

    public string HearingRight { get; set; }

    public string DentalHealth { get; set; }

    public string OtherFindings { get; set; }

    public string ConsultationDate { get; set; }

    public bool? IsActive { get; set; }

    public virtual CheckUpScheduleHuyLq CheckupScheduleHuyLq { get; set; }
}