// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SMMS.Repositories.NghiaHT.Models;

public partial class StudentHealthProfilesTienVln
{
    public int StudentHealthProfilesTienVlnid { get; set; }

    public decimal? Height { get; set; }

    public decimal? Weight { get; set; }

    public decimal? Bmi { get; set; }

    public string BloodType { get; set; }

    public int? Vision { get; set; }

    public string Hearing { get; set; }

    public string DentalHealth { get; set; }

    public string Allergies { get; set; }

    public string PastSurgeries { get; set; }

    public string FamilymedicalHistory { get; set; }

    public int? HealthProfileTypesTienVlnid { get; set; }

    public bool? IsApproved { get; set; }

    public DateTime? CreatedDate { get; set; }

    public virtual HealthProfileTypesTienVln HealthProfileTypesTienVln { get; set; }
}