// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SMMS.Repositories.NghiaHT.Models;

public partial class VaccineTypeLongTn
{
    public int VaccineTypeLongTnid { get; set; }

    public string TypeName { get; set; }

    public string Description { get; set; }

    public virtual ICollection<VaccinationLongTn> VaccinationLongTns { get; set; } = new List<VaccinationLongTn>();
}