// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SMMS.Repositories.NghiaHT.Models;

public partial class VaccinationLongTn
{
    public int VaccinationLongTnid { get; set; }

    public string VaccineName { get; set; }

    public int? VaccineTypeLongTnid { get; set; }

    public int? DoseNumber { get; set; }

    public DateTime? ScheduleDate { get; set; }

    public DateTime? ActualDate { get; set; }

    public string InjectionSite { get; set; }

    public string DoctorOrNurseName { get; set; }

    public string ReactionAfterVaccination { get; set; }

    public string Notes { get; set; }

    public bool? IsFollowUpRequired { get; set; }

    public DateTime? FollowUpdate { get; set; }

    public virtual VaccineTypeLongTn VaccineTypeLongTn { get; set; }
}